/* eslint-disable */
// This file is generated by esbuild and is intended to run inside Obsidian.
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MoveAttachmentsWithNotePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/companion.ts
var import_obsidian = require("obsidian");
var MAX_SUFFIX_ATTEMPTS = 1e4;
function getDirectory(path) {
  const normalized = (0, import_obsidian.normalizePath)(path);
  const splitIndex = normalized.lastIndexOf("/");
  return splitIndex === -1 ? "" : normalized.slice(0, splitIndex);
}
function buildPath(dir, fileName) {
  return dir.length > 0 ? (0, import_obsidian.normalizePath)(`${dir}/${fileName}`) : (0, import_obsidian.normalizePath)(fileName);
}
function buildNumberedName(fileName, suffix) {
  const extIndex = fileName.lastIndexOf(".");
  if (extIndex <= 0) {
    return `${fileName}-${suffix}`;
  }
  const base = fileName.slice(0, extIndex);
  const ext = fileName.slice(extIndex);
  return `${base}-${suffix}${ext}`;
}
function isEligibleFile(file) {
  return file instanceof import_obsidian.TFile && file.extension.toLowerCase() !== "md";
}
function buildCompanionContent(linktext) {
  const source = JSON.stringify(`[[${linktext}]]`);
  return `---
source: ${source}
---
![[${linktext}]]
`;
}
function setCanonicalSource(frontmatter, sourceLink) {
  const parsed = (0, import_obsidian.parseYaml)(frontmatter);
  if (parsed != null && (typeof parsed !== "object" || Array.isArray(parsed))) {
    throw new Error("Companion note model frontmatter must be a YAML mapping");
  }
  const sourceLine = `source: ${JSON.stringify(sourceLink)}`;
  const lines = frontmatter.split(/\r?\n/);
  const sourceIndex = lines.findIndex((line) => /^(?:source|["']source["'])\s*:/.test(line));
  if (sourceIndex === -1) {
    while (lines[lines.length - 1] === "") {
      lines.pop();
    }
    lines.push(sourceLine);
    return lines.join("\n");
  }
  let endIndex = sourceIndex + 1;
  while (endIndex < lines.length && (/^\s/.test(lines[endIndex]) || lines[endIndex].trim() === "")) {
    endIndex += 1;
  }
  lines.splice(sourceIndex, endIndex - sourceIndex, sourceLine);
  return lines.join("\n");
}
function removeTopLevelProperty(frontmatter, property) {
  const lines = frontmatter.split(/\r?\n/);
  const propertyPattern = new RegExp(`^(?:${property}|["']${property}["'])\\s*:`);
  const propertyIndex = lines.findIndex((line) => propertyPattern.test(line));
  if (propertyIndex === -1) {
    return frontmatter;
  }
  let endIndex = propertyIndex + 1;
  while (endIndex < lines.length && (/^\s/.test(lines[endIndex]) || lines[endIndex].trim() === "")) {
    endIndex += 1;
  }
  lines.splice(propertyIndex, endIndex - propertyIndex);
  return lines.join("\n");
}
function setCanonicalSources(frontmatter, sourceLinks) {
  const withoutSingular = removeTopLevelProperty(frontmatter, "source");
  const withoutExisting = removeTopLevelProperty(withoutSingular, "sources").trimEnd();
  const sourcesBlock = [
    "sources:",
    ...sourceLinks.map((sourceLink) => `  - ${JSON.stringify(sourceLink)}`)
  ].join("\n");
  return withoutExisting.length === 0 ? sourcesBlock : `${withoutExisting}
${sourcesBlock}`;
}
function expandStandardPlaceholders(content, title, now) {
  const timestamp = (0, import_obsidian.moment)(now);
  return content.replace(
    /\{\{date(?::([^}]+))?\}\}/g,
    (_match, format) => timestamp.format(format ?? "YYYY-MM-DD")
  ).replace(
    /\{\{time(?::([^}]+))?\}\}/g,
    (_match, format) => timestamp.format(format ?? "HH:mm")
  ).replace(/\{\{title\}\}/g, () => title);
}
function splitModelContent(content) {
  const frontmatterMatch = content.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/);
  if (frontmatterMatch == null) {
    return { frontmatter: "", body: content };
  }
  const parsed = (0, import_obsidian.parseYaml)(frontmatterMatch[1]);
  if (parsed != null && (typeof parsed !== "object" || Array.isArray(parsed))) {
    throw new Error("Note model frontmatter must be a YAML mapping");
  }
  return {
    frontmatter: frontmatterMatch[1],
    body: content.slice(frontmatterMatch[0].length)
  };
}
function buildCompanionContentFromModel(modelContent, linktext, title, now = Date.now()) {
  const sourceLink = `[[${linktext}]]`;
  const embed = `![[${linktext}]]`;
  const hadEmbedPlaceholder = modelContent.includes("{{embed}}");
  let content = expandStandardPlaceholders(modelContent, title, now).replace(/\{\{source\}\}/g, () => sourceLink).replace(/\{\{embed\}\}/g, () => embed);
  if (!hadEmbedPlaceholder) {
    content = `${content.trimEnd()}${content.trim().length > 0 ? "\n" : ""}${embed}
`;
  } else if (!content.endsWith("\n")) {
    content += "\n";
  }
  const { frontmatter, body } = splitModelContent(content);
  return `---
${setCanonicalSource(frontmatter, sourceLink)}
---
${body}`;
}
function getCommonDirectory(files) {
  if (files.length === 0) {
    return "";
  }
  const directories = files.map((file) => getDirectory(file.path).split("/").filter(Boolean));
  const common = [];
  for (let index = 0; index < directories[0].length; index += 1) {
    const segment = directories[0][index];
    if (directories.every((directory) => directory[index] === segment)) {
      common.push(segment);
    } else {
      break;
    }
  }
  return common.join("/");
}
function findAvailableCollectionPath(app, sourceFiles, now = Date.now()) {
  const directory = getCommonDirectory(sourceFiles);
  const fileName = `${(0, import_obsidian.moment)(now).format("YYYY-MM-DD HH.mm")} Collection.md`;
  const primaryPath = buildPath(directory, fileName);
  if (app.vault.getAbstractFileByPath(primaryPath) == null) {
    return primaryPath;
  }
  for (let suffix = 1; suffix <= MAX_SUFFIX_ATTEMPTS; suffix += 1) {
    const candidatePath = buildPath(directory, buildNumberedName(fileName, suffix));
    if (app.vault.getAbstractFileByPath(candidatePath) == null) {
      return candidatePath;
    }
  }
  return null;
}
function buildCollectionContent(linktexts, modelContent, title, now = Date.now()) {
  const sourceLinks = linktexts.map((linktext) => `[[${linktext}]]`);
  const embeds = linktexts.map((linktext) => `![[${linktext}]]`).join("\n");
  if (modelContent == null) {
    return `---
${setCanonicalSources("", sourceLinks)}
---
${embeds}
`;
  }
  const hadEmbedsPlaceholder = modelContent.includes("{{embeds}}");
  let content = expandStandardPlaceholders(modelContent, title, now).replace(/\{\{sources\}\}/g, () => sourceLinks.map((link) => `- ${link}`).join("\n")).replace(/\{\{embeds\}\}/g, () => embeds);
  if (!hadEmbedsPlaceholder) {
    content = `${content.trimEnd()}${content.trim().length > 0 ? "\n" : ""}${embeds}
`;
  } else if (!content.endsWith("\n")) {
    content += "\n";
  }
  const { frontmatter, body } = splitModelContent(content);
  return `---
${setCanonicalSources(frontmatter, sourceLinks)}
---
${body}`;
}
async function createCollectionNote(app, sourceFiles, modelContent = null, now = Date.now()) {
  const currentFiles = [];
  for (const sourceFile of sourceFiles) {
    const current = app.vault.getAbstractFileByPath(sourceFile.path);
    if (!isEligibleFile(current)) {
      return { kind: "error", error: new Error(`Source file is no longer available: ${sourceFile.path}`) };
    }
    currentFiles.push(current);
  }
  if (currentFiles.length < 2) {
    return { kind: "error", error: new Error("A collection note requires at least two source files") };
  }
  const targetPath = findAvailableCollectionPath(app, currentFiles, now);
  if (targetPath == null) {
    return { kind: "error", error: new Error("Could not allocate a collection note name") };
  }
  const linktexts = currentFiles.map((file) => app.metadataCache.fileToLinktext(file, targetPath, false));
  const targetFileName = targetPath.slice(targetPath.lastIndexOf("/") + 1);
  let content;
  try {
    content = buildCollectionContent(linktexts, modelContent, targetFileName.slice(0, -3), now);
  } catch (error) {
    return { kind: "error", error };
  }
  try {
    const note = await app.vault.create(targetPath, content);
    return { kind: "created", note, path: targetPath };
  } catch (error) {
    return { kind: "error", error };
  }
}
function findAvailableCompanionPath(app, sourceFile) {
  const directory = getDirectory(sourceFile.path);
  const primaryPath = buildPath(directory, `${sourceFile.basename}.md`);
  if (app.vault.getAbstractFileByPath(primaryPath) == null) {
    return { path: primaryPath, conflictResolved: false };
  }
  const token = sourceFile.extension.length > 0 ? sourceFile.extension : "file";
  const fallbackStem = `${sourceFile.basename} - ${token}`;
  const fallbackPath = buildPath(directory, `${fallbackStem}.md`);
  if (app.vault.getAbstractFileByPath(fallbackPath) == null) {
    return { path: fallbackPath, conflictResolved: true };
  }
  for (let suffix = 1; suffix <= MAX_SUFFIX_ATTEMPTS; suffix += 1) {
    const candidatePath = buildPath(directory, `${fallbackStem}-${suffix}.md`);
    if (app.vault.getAbstractFileByPath(candidatePath) == null) {
      return { path: candidatePath, conflictResolved: true };
    }
  }
  return null;
}
function getCanonicalSourceLink(cache) {
  if (typeof cache.frontmatter?.source !== "string") {
    return null;
  }
  const value = cache.frontmatter.source.trim();
  if (!/^\[\[[^\]]+\]\]$/.test(value)) {
    return null;
  }
  const sourceLinks = (cache.frontmatterLinks ?? []).filter((link) => link.key === "source");
  return sourceLinks.length === 1 ? sourceLinks[0].link : null;
}
function buildCompanionIndex(app) {
  const bySourcePath = /* @__PURE__ */ new Map();
  const missingMetadata = [];
  for (const note of app.vault.getMarkdownFiles()) {
    const cache = app.metadataCache.getFileCache(note);
    if (cache == null) {
      missingMetadata.push(note.path);
      continue;
    }
    const sourceLink = getCanonicalSourceLink(cache);
    if (sourceLink == null) {
      continue;
    }
    const sourceFile = app.metadataCache.getFirstLinkpathDest(sourceLink, note.path);
    if (!isEligibleFile(sourceFile)) {
      continue;
    }
    const companions = bySourcePath.get(sourceFile.path) ?? [];
    companions.push(note);
    bySourcePath.set(sourceFile.path, companions);
  }
  return { bySourcePath, missingMetadata };
}
async function createCompanionIfNeeded(app, sourceFile, index, modelContent = null, now = Date.now()) {
  const existing = index.bySourcePath.get(sourceFile.path) ?? [];
  if (existing.length > 1) {
    return { kind: "ambiguous", notes: existing };
  }
  if (existing.length === 1) {
    return { kind: "alreadyExisting", note: existing[0] };
  }
  const currentFile = app.vault.getAbstractFileByPath(sourceFile.path);
  if (!isEligibleFile(currentFile)) {
    return { kind: "error", error: new Error(`Source file is no longer available: ${sourceFile.path}`) };
  }
  const target = findAvailableCompanionPath(app, currentFile);
  if (target == null) {
    return {
      kind: "error",
      error: new Error(
        `Could not allocate a companion name after ${MAX_SUFFIX_ATTEMPTS} numbered attempts`
      )
    };
  }
  const linktext = app.metadataCache.fileToLinktext(currentFile, target.path, false);
  let content;
  try {
    const targetFileName = target.path.slice(target.path.lastIndexOf("/") + 1);
    content = modelContent == null ? buildCompanionContent(linktext) : buildCompanionContentFromModel(
      modelContent,
      linktext,
      targetFileName.slice(0, -3),
      now
    );
  } catch (error) {
    return { kind: "error", error };
  }
  try {
    const note = await app.vault.create(target.path, content);
    index.bySourcePath.set(currentFile.path, [note]);
    return {
      kind: "created",
      note,
      path: target.path,
      conflictResolved: target.conflictResolved
    };
  } catch (error) {
    return { kind: "error", error };
  }
}

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  companionTemplatePath: "",
  collectionTemplatePath: ""
};
var MarkdownFileSuggest = class extends import_obsidian2.AbstractInputSuggest {
  constructor(app, input, onChoose) {
    super(app, input.inputEl);
    this.onSelect(onChoose);
  }
  getSuggestions(query) {
    const normalizedQuery = query.trim().toLowerCase();
    return this.app.vault.getMarkdownFiles().filter((file) => normalizedQuery.length === 0 || file.path.toLowerCase().includes(normalizedQuery)).slice(0, 100);
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
};
var MoveAttachmentsWithNoteSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, owner) {
    super(app, owner);
    this.owner = owner;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Companion note model").setDesc("Choose any Markdown note in the vault to use as the model for new companion notes. Leave blank to use the built-in minimal content.").addText((text) => {
      text.setPlaceholder("Path/to/model.md").setValue(this.owner.settings.companionTemplatePath).onChange(async (value) => {
        this.owner.settings.companionTemplatePath = value.trim().length === 0 ? "" : (0, import_obsidian2.normalizePath)(value.trim());
        await this.owner.saveSettings();
      });
      new MarkdownFileSuggest(this.app, text, (file) => {
        text.setValue(file.path);
        this.owner.settings.companionTemplatePath = file.path;
        void this.owner.saveSettings();
      });
    });
    new import_obsidian2.Setting(containerEl).setName("Collection note model").setDesc("Choose any Markdown note in the vault to use as the model for notes created from multiple selected files. Leave blank to use the built-in minimal content.").addText((text) => {
      text.setPlaceholder("Path/to/model.md").setValue(this.owner.settings.collectionTemplatePath).onChange(async (value) => {
        this.owner.settings.collectionTemplatePath = value.trim().length === 0 ? "" : (0, import_obsidian2.normalizePath)(value.trim());
        await this.owner.saveSettings();
      });
      new MarkdownFileSuggest(this.app, text, (file) => {
        text.setValue(file.path);
        this.owner.settings.collectionTemplatePath = file.path;
        void this.owner.saveSettings();
      });
    });
  }
};

// src/main.ts
var LOG_PREFIX = "[move-attachments-with-note]";
var LINK_CACHE_DELAY_MS = 150;
var FILE_EXPLORER_MENU_SOURCE = "file-explorer-context-menu";
var NOTEBOOK_NAVIGATOR_PLUGIN_ID = "notebook-navigator";
var NOTEBOOK_NAVIGATOR_RETRY_INTERVAL_MS = 250;
var NOTEBOOK_NAVIGATOR_MAX_RETRIES = 40;
function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
var MoveAttachmentsWithNotePlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.notebookNavigatorMenusRegistered = false;
    this.notebookNavigatorRegistrationTimer = null;
  }
  async onload() {
    console.info(`${LOG_PREFIX} loaded`);
    await this.loadSettings();
    this.addSettingTab(new MoveAttachmentsWithNoteSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        void this.handleRename(file, oldPath);
        void this.handleTemplateRename(file, oldPath);
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file, source) => {
        if (source === FILE_EXPLORER_MENU_SOURCE && isEligibleFile(file)) {
          this.addSingleCompanionMenuItem(menu, file);
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("files-menu", (menu, files) => {
        if (files.length >= 2 && files.some(isEligibleFile)) {
          this.addBatchCompanionMenuItem(menu, files);
        }
      })
    );
    this.addCommand({
      id: "open-or-create-companion-note-for-active-file",
      name: "Open or create companion note for active file",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        const available = isEligibleFile(file);
        if (available && !checking) {
          void this.openOrCreateCompanion(file);
        }
        return available;
      }
    });
    this.app.workspace.onLayoutReady(() => {
      this.startNotebookNavigatorRegistration();
    });
    this.register(() => {
      if (this.notebookNavigatorRegistrationTimer != null) {
        clearTimeout(this.notebookNavigatorRegistrationTimer);
      }
    });
  }
  onunload() {
    console.info(`${LOG_PREFIX} unloaded`);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async handleTemplateRename(file, oldPath) {
    if (!(file instanceof import_obsidian3.TFile)) {
      return;
    }
    let changed = false;
    if (oldPath === this.settings.companionTemplatePath) {
      this.settings.companionTemplatePath = file.path;
      changed = true;
    }
    if (oldPath === this.settings.collectionTemplatePath) {
      this.settings.collectionTemplatePath = file.path;
      changed = true;
    }
    if (changed) {
      await this.saveSettings();
    }
  }
  async readNoteModelOrNotify(path, label) {
    if (path.length === 0) {
      return null;
    }
    const model = this.app.vault.getAbstractFileByPath(path);
    if (!(model instanceof import_obsidian3.TFile) || model.extension.toLowerCase() !== "md") {
      console.error(`${LOG_PREFIX} ${label} is unavailable: ${path}`);
      new import_obsidian3.Notice(`${label} is unavailable: ${path}`);
      return void 0;
    }
    try {
      return await this.app.vault.cachedRead(model);
    } catch (error) {
      console.error(`${LOG_PREFIX} Could not read ${label.toLowerCase()}: ${path}`, error);
      new import_obsidian3.Notice(`Could not read ${label.toLowerCase()}: ${path}`);
      return void 0;
    }
  }
  readCompanionTemplateOrNotify() {
    return this.readNoteModelOrNotify(this.settings.companionTemplatePath, "Companion note model");
  }
  readCollectionTemplateOrNotify() {
    return this.readNoteModelOrNotify(this.settings.collectionTemplatePath, "Collection note model");
  }
  addSingleCompanionMenuItem(menu, file) {
    menu.addItem((item) => {
      item.setTitle("Open or create companion note").setIcon("file-plus-2").onClick(() => this.openOrCreateCompanion(file));
    });
  }
  addBatchCompanionMenuItem(menu, files) {
    menu.addItem((item) => {
      item.setTitle("Create companion notes").setIcon("files").onClick(() => this.createCompanionBatch(files));
    });
    if (files.filter(isEligibleFile).length >= 2) {
      menu.addItem((item) => {
        item.setTitle("Create collection note from selected files").setIcon("notebook-tabs").onClick(() => this.createCollectionFromSelection(files));
      });
    }
  }
  async createCollectionFromSelection(files) {
    const eligibleFiles = files.filter(isEligibleFile);
    if (eligibleFiles.length < 2) {
      new import_obsidian3.Notice("Select at least two non-Markdown files to create a collection note.");
      return;
    }
    const modelContent = await this.readCollectionTemplateOrNotify();
    if (modelContent === void 0) {
      return;
    }
    const result = await createCollectionNote(this.app, eligibleFiles, modelContent);
    if (result.kind === "error") {
      console.error(`${LOG_PREFIX} Failed to create collection note`, result.error);
      new import_obsidian3.Notice("Could not create a collection note for the selected files.");
      return;
    }
    console.info(`${LOG_PREFIX} Collection note created: ${result.path} (${eligibleFiles.length} sources)`);
    try {
      await this.app.workspace.getLeaf(false).openFile(result.note);
    } catch (error) {
      console.error(`${LOG_PREFIX} Failed to open collection note ${result.path}`, error);
      new import_obsidian3.Notice(`Collection note exists but could not be opened: ${result.path}`);
    }
  }
  async openOrCreateCompanion(file) {
    const index = this.getCompanionIndexOrNotify();
    if (index == null) {
      return;
    }
    let modelContent = null;
    if ((index.bySourcePath.get(file.path) ?? []).length === 0) {
      const loadedModel = await this.readCompanionTemplateOrNotify();
      if (loadedModel === void 0) {
        return;
      }
      modelContent = loadedModel;
    }
    const result = await createCompanionIfNeeded(this.app, file, index, modelContent);
    if (result.kind === "ambiguous") {
      const paths = result.notes.map((note) => note.path).join(", ");
      console.error(`${LOG_PREFIX} Ambiguous companion association for ${file.path}: ${paths}`);
      new import_obsidian3.Notice(`Multiple companion notes declare ${file.name} as source: ${paths}`);
      return;
    }
    if (result.kind === "error") {
      console.error(`${LOG_PREFIX} Failed to create companion for ${file.path}`, result.error);
      new import_obsidian3.Notice(`Could not open or create a companion note for ${file.name}.`);
      return;
    }
    if (result.kind === "created") {
      if (result.conflictResolved) {
        console.warn(`${LOG_PREFIX} Companion name conflict for ${file.path}; using ${result.path}`);
      }
      console.info(`${LOG_PREFIX} Companion created: ${result.note.path} (source: ${file.path})`);
    } else {
      console.info(`${LOG_PREFIX} Existing companion found: ${result.note.path} (source: ${file.path})`);
    }
    try {
      await this.app.workspace.getLeaf(false).openFile(result.note);
    } catch (error) {
      console.error(`${LOG_PREFIX} Failed to open companion ${result.note.path}`, error);
      new import_obsidian3.Notice(`Companion note exists but could not be opened: ${result.note.path}`);
    }
  }
  async createCompanionBatch(files) {
    const eligibleFiles = files.filter(isEligibleFile);
    const ignored = files.length - eligibleFiles.length;
    const index = this.getCompanionIndexOrNotify(false);
    if (index == null) {
      this.showBatchSummary(0, 0, ignored, eligibleFiles.length);
      return;
    }
    let created = 0;
    let alreadyExisting = 0;
    let errors = 0;
    let modelLoaded = false;
    let modelContent = null;
    for (const file of eligibleFiles) {
      if ((index.bySourcePath.get(file.path) ?? []).length === 0 && !modelLoaded) {
        modelContent = await this.readCompanionTemplateOrNotify();
        modelLoaded = true;
      }
      if ((index.bySourcePath.get(file.path) ?? []).length === 0 && modelContent === void 0) {
        errors += 1;
        continue;
      }
      const result = await createCompanionIfNeeded(this.app, file, index, modelContent ?? null);
      if (result.kind === "created") {
        created += 1;
        if (result.conflictResolved) {
          console.warn(`${LOG_PREFIX} Companion name conflict for ${file.path}; using ${result.path}`);
        }
        console.info(`${LOG_PREFIX} Companion created: ${result.note.path} (source: ${file.path})`);
      } else if (result.kind === "alreadyExisting") {
        alreadyExisting += 1;
        console.info(`${LOG_PREFIX} Existing companion found: ${result.note.path} (source: ${file.path})`);
      } else if (result.kind === "ambiguous") {
        errors += 1;
        console.error(
          `${LOG_PREFIX} Ambiguous companion association for ${file.path}: ${result.notes.map((note) => note.path).join(", ")}`
        );
      } else {
        errors += 1;
        console.error(`${LOG_PREFIX} Failed to create companion for ${file.path}`, result.error);
      }
    }
    this.showBatchSummary(created, alreadyExisting, ignored, errors);
  }
  getCompanionIndexOrNotify(notify = true) {
    const index = buildCompanionIndex(this.app);
    if (index.missingMetadata.length === 0) {
      return index;
    }
    console.error(
      `${LOG_PREFIX} Companion discovery stopped because metadata is unavailable for: ${index.missingMetadata.join(", ")}`
    );
    if (notify) {
      new import_obsidian3.Notice("Companion notes could not be checked because Obsidian metadata is not ready.");
    }
    return null;
  }
  showBatchSummary(created, alreadyExisting, ignored, errors) {
    const parts = [`${created} created`, `${alreadyExisting} already existed`];
    if (ignored > 0) {
      parts.push(`${ignored} ignored`);
    }
    parts.push(`${errors} failed`);
    const message = `Companion notes: ${parts.join(", ")}.`;
    console.info(`${LOG_PREFIX} ${message}`);
    new import_obsidian3.Notice(message);
  }
  startNotebookNavigatorRegistration() {
    let attempts = 0;
    const tryRegistration = () => {
      this.notebookNavigatorRegistrationTimer = null;
      if (this.registerNotebookNavigatorMenus()) {
        return;
      }
      attempts += 1;
      if (attempts >= NOTEBOOK_NAVIGATOR_MAX_RETRIES) {
        return;
      }
      this.notebookNavigatorRegistrationTimer = setTimeout(
        tryRegistration,
        NOTEBOOK_NAVIGATOR_RETRY_INTERVAL_MS
      );
    };
    tryRegistration();
  }
  registerNotebookNavigatorMenus() {
    if (this.notebookNavigatorMenusRegistered) {
      return true;
    }
    const registry = this.app.plugins;
    const plugin = registry?.getPlugin?.(NOTEBOOK_NAVIGATOR_PLUGIN_ID) ?? registry?.plugins?.[NOTEBOOK_NAVIGATOR_PLUGIN_ID];
    const api = plugin?.api;
    if (api == null || typeof api.getVersion !== "function" || typeof api.menus?.registerFileMenu !== "function") {
      return false;
    }
    const majorVersion = Number.parseInt(api.getVersion().split(".")[0] ?? "", 10);
    if (!Number.isFinite(majorVersion) || majorVersion < 2) {
      console.warn(`${LOG_PREFIX} Notebook Navigator 2.0.0 or newer is required for menu integration`);
      return true;
    }
    const dispose = api.menus.registerFileMenu((context) => {
      if (context.selection.mode === "multiple") {
        if (context.selection.files.length >= 2 && context.selection.files.some(isEligibleFile)) {
          context.addItem((item) => {
            item.setTitle("Create companion notes");
            item.setIcon("files");
            item.onClick(() => this.createCompanionBatch(context.selection.files));
          });
          if (context.selection.files.filter(isEligibleFile).length >= 2) {
            context.addItem((item) => {
              item.setTitle("Create collection note from selected files");
              item.setIcon("notebook-tabs");
              item.onClick(() => this.createCollectionFromSelection(context.selection.files));
            });
          }
        }
        return;
      }
      if (isEligibleFile(context.file)) {
        context.addItem((item) => {
          item.setTitle("Open or create companion note");
          item.setIcon("file-plus-2");
          item.onClick(() => this.openOrCreateCompanion(context.file));
        });
      }
    });
    this.notebookNavigatorMenusRegistered = true;
    this.register(dispose);
    console.info(`${LOG_PREFIX} Notebook Navigator companion menus registered`);
    return true;
  }
  async handleRename(file, oldPath) {
    if (!(file instanceof import_obsidian3.TFile)) {
      return;
    }
    if (file.extension.toLowerCase() !== "md") {
      return;
    }
    const oldDir = getDirectory(oldPath);
    const newDir = getDirectory(file.path);
    if (oldDir === newDir) {
      return;
    }
    await sleep(LINK_CACHE_DELAY_MS);
    const linkedPaths = this.getLinkedPaths(file.path, oldPath);
    if (linkedPaths.length === 0) {
      console.info(
        `${LOG_PREFIX} No resolved links found for moved note: ${file.path} (oldPath: ${oldPath})`
      );
      return;
    }
    let movedCount = 0;
    let sharedSkippedCount = 0;
    let folderSkippedCount = 0;
    let brokenSkippedCount = 0;
    let markdownSkippedCount = 0;
    let errorCount = 0;
    for (const linkedPath of linkedPaths) {
      const candidate = this.app.vault.getAbstractFileByPath(linkedPath);
      if (!(candidate instanceof import_obsidian3.TFile)) {
        brokenSkippedCount += 1;
        console.warn(
          `${LOG_PREFIX} Ignoring unresolved attachment link: ${linkedPath} (note: ${file.path})`
        );
        continue;
      }
      if (candidate.extension.toLowerCase() === "md") {
        markdownSkippedCount += 1;
        continue;
      }
      if (getDirectory(candidate.path) !== oldDir) {
        folderSkippedCount += 1;
        continue;
      }
      if (this.isSharedAttachment(candidate.path, file.path, oldPath)) {
        sharedSkippedCount += 1;
        console.info(
          `${LOG_PREFIX} Ignoring shared attachment: ${candidate.path} (note: ${file.path})`
        );
        continue;
      }
      const target = this.findAvailableTargetPath(newDir, candidate.name);
      if (target == null) {
        errorCount += 1;
        console.error(
          `${LOG_PREFIX} Could not allocate destination name after ${MAX_SUFFIX_ATTEMPTS} attempts for ${candidate.path}`
        );
        continue;
      }
      if (target.suffix > 0) {
        console.warn(
          `${LOG_PREFIX} Destination conflict for ${candidate.path}; using ${target.path}`
        );
      }
      try {
        await this.app.fileManager.renameFile(candidate, target.path);
        movedCount += 1;
      } catch (error) {
        errorCount += 1;
        console.error(
          `${LOG_PREFIX} Failed to move attachment ${candidate.path} -> ${target.path}`,
          error
        );
      }
    }
    console.info(
      `${LOG_PREFIX} Move summary for ${file.path}: moved=${movedCount}, skippedShared=${sharedSkippedCount}, skippedFolder=${folderSkippedCount}, skippedBroken=${brokenSkippedCount}, skippedMarkdown=${markdownSkippedCount}, errors=${errorCount}`
    );
  }
  getLinkedPaths(newPath, oldPath) {
    const resolvedLinks = this.app.metadataCache.resolvedLinks;
    const fromNewPath = resolvedLinks[newPath] ?? {};
    const fromOldPath = resolvedLinks[oldPath] ?? {};
    const merged = { ...fromOldPath, ...fromNewPath };
    return Object.keys(merged);
  }
  isSharedAttachment(attachmentPath, newNotePath, oldNotePath) {
    const resolvedLinks = this.app.metadataCache.resolvedLinks;
    for (const [sourcePath, outgoingLinks] of Object.entries(resolvedLinks)) {
      if (!sourcePath.toLowerCase().endsWith(".md")) {
        continue;
      }
      if (sourcePath === newNotePath || sourcePath === oldNotePath) {
        continue;
      }
      if (Object.prototype.hasOwnProperty.call(outgoingLinks, attachmentPath)) {
        return true;
      }
    }
    return false;
  }
  findAvailableTargetPath(destinationDirectory, originalFileName) {
    const firstCandidate = buildPath(destinationDirectory, originalFileName);
    if (this.app.vault.getAbstractFileByPath(firstCandidate) == null) {
      return { path: firstCandidate, suffix: 0 };
    }
    for (let suffix = 1; suffix <= MAX_SUFFIX_ATTEMPTS; suffix += 1) {
      const numberedName = buildNumberedName(originalFileName, suffix);
      const candidatePath = buildPath(destinationDirectory, numberedName);
      if (this.app.vault.getAbstractFileByPath(candidatePath) == null) {
        return { path: candidatePath, suffix };
      }
    }
    return null;
  }
};
